version: '3.7'
services:
    web:
        build: .
        ports:
            - "10000:8000"
        volumes:
            - .:/app
        links:
            - db

    db:
        image: "postgres:12-alpine"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: ncEMplEdAGOduCkLaCotWeDisant