# Generated by Django 2.2.10 on 2020-02-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, default='-', max_length=10, verbose_name='学号'),
        ),
    ]
