# Generated by Django 2.2.10 on 2020-02-18 16:29

import api.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=api.models.get_default_json, verbose_name='课程'),
        ),
    ]
